/*
 * This file was automatically generated by sel-utils and
 * released under the MIT License.
 * 
 * License: https://github.com/sel-project/sel-utils/blob/master/LICENSE
 * Repository: https://github.com/sel-project/sel-utils
 * Generated from https://github.com/sel-project/sel-utils/blob/master/xml/protocol/java338.xml
 */
package sul.protocol.java338.serverbound;

import sul.utils.*;

public class ClientStatus extends Packet {

	public static final int ID = (int)3;

	public static final boolean CLIENTBOUND = false;
	public static final boolean SERVERBOUND = true;

	@Override
	public int getId() {
		return ID;
	}

	// action
	public static final int RESPAWN = (int)0;
	public static final int REQUEST_STATS = (int)1;

	public int action;

	public ClientStatus() {}

	public ClientStatus(int action) {
		this.action = action;
	}

	@Override
	public int length() {
		return Buffer.varuintLength(action) + 1;
	}

	@Override
	public byte[] encode() {
		this._buffer = new byte[this.length()];
		this.writeVaruint(ID);
		this.writeVaruint(action);
		return this.getBuffer();
	}

	@Override
	public void decode(byte[] buffer) {
		this._buffer = buffer;
		this.readVaruint();
		action=this.readVaruint();
	}

	public static ClientStatus fromBuffer(byte[] buffer) {
		ClientStatus ret = new ClientStatus();
		ret.decode(buffer);
		return ret;
	}

	@Override
	public String toString() {
		return "ClientStatus(action: " + this.action + ")";
	}

}