/*
 * This file was automatically generated by sel-utils and
 * released under the MIT License.
 * 
 * License: https://github.com/sel-project/sel-utils/blob/master/LICENSE
 * Repository: https://github.com/sel-project/sel-utils
 * Generated from https://github.com/sel-project/sel-utils/blob/master/xml/protocol/pocket111.xml
 */
package sul.protocol.pocket111.types;

import java.util.Arrays;

import sul.utils.*;

public class LoginBody extends Stream {

	public byte[] chain = new byte[0];
	public byte[] clientData = new byte[0];

	public LoginBody() {}

	public LoginBody(byte[] chain, byte[] clientData) {
		this.chain = chain;
		this.clientData = clientData;
	}

	@Override
	public int length() {
		return chain.length + clientData.length + 8;
	}

	@Override
	public byte[] encode() {
		this._buffer = new byte[this.length()];
		this.writeLittleEndianInt((int)chain.length); this.writeBytes(chain);
		this.writeLittleEndianInt((int)clientData.length); this.writeBytes(clientData);
		return this.getBuffer();
	}

	@Override
	public void decode(byte[] buffer) {
		this._buffer = buffer;
		int bnyl=readLittleEndianInt(); chain=this.readBytes(bnyl);
		int bnavdrde=readLittleEndianInt(); clientData=this.readBytes(bnavdrde);
	}

	@Override
	public String toString() {
		return "LoginBody(chain: " + Arrays.toString(this.chain) + ", clientData: " + Arrays.toString(this.clientData) + ")";
	}


}