/*
 * This file was automatically generated by sel-utils and
 * released under the MIT License.
 * 
 * License: https://github.com/sel-project/sel-utils/blob/master/LICENSE
 * Repository: https://github.com/sel-project/sel-utils
 * Generated from https://github.com/sel-project/sel-utils/blob/master/xml/protocol/pocket131.xml
 */
package sul.protocol.pocket131.play;

import java.nio.charset.StandardCharsets;

import sul.utils.*;

public class CommandRequest extends Packet {

	public static final int ID = (int)77;

	public static final boolean CLIENTBOUND = false;
	public static final boolean SERVERBOUND = true;

	@Override
	public int getId() {
		return ID;
	}

	// type
	public static final int PLAYER = 0;
	public static final int COMMAND_BLOCK = 1;
	public static final int MINECART_COMMAND_BLOCK = 2;
	public static final int DEV_CONSOLE = 3;

	public String command;
	public int type;
	public String requestId;
	public int playerId;

	public CommandRequest() {}

	public CommandRequest(String command, int type, String requestId, int playerId) {
		this.command = command;
		this.type = type;
		this.requestId = requestId;
		this.playerId = playerId;
	}

	@Override
	public int length() {
		return Buffer.varuintLength(command.getBytes(StandardCharsets.UTF_8).length) + command.getBytes(StandardCharsets.UTF_8).length + Buffer.varuintLength(type) + Buffer.varuintLength(requestId.getBytes(StandardCharsets.UTF_8).length) + requestId.getBytes(StandardCharsets.UTF_8).length + Buffer.varintLength(playerId) + 2;
	}

	@Override
	public byte[] encode() {
		this._buffer = new byte[this.length()];
		this.writeVaruint(ID);
		byte[] y9bfz=command.getBytes(StandardCharsets.UTF_8); this.writeVaruint((int)y9bfz.length); this.writeBytes(y9bfz);
		this.writeVaruint(type);
		byte[] cvdvdl=requestId.getBytes(StandardCharsets.UTF_8); this.writeVaruint((int)cvdvdl.length); this.writeBytes(cvdvdl);
		if(type==3){ this.writeVarint(playerId); }
		return this.getBuffer();
	}

	@Override
	public void decode(byte[] buffer) {
		this._buffer = buffer;
		this.readVaruint();
		int bvy9bfz=this.readVaruint(); command=new String(this.readBytes(bvy9bfz), StandardCharsets.UTF_8);
		type=this.readVaruint();
		int bvcvdvdl=this.readVaruint(); requestId=new String(this.readBytes(bvcvdvdl), StandardCharsets.UTF_8);
		if(type==3){ playerId=this.readVarint(); }
	}

	public static CommandRequest fromBuffer(byte[] buffer) {
		CommandRequest ret = new CommandRequest();
		ret.decode(buffer);
		return ret;
	}

	@Override
	public String toString() {
		return "CommandRequest(command: " + this.command + ", type: " + this.type + ", requestId: " + this.requestId + ", playerId: " + this.playerId + ")";
	}

}