/*
 * This file was automatically generated by sel-utils and
 * released under the MIT License.
 * 
 * License: https://github.com/sel-project/sel-utils/blob/master/LICENSE
 * Repository: https://github.com/sel-project/sel-utils
 * Generated from https://github.com/sel-project/sel-utils/blob/master/xml/protocol/pocket131.xml
 */
package sul.protocol.pocket131.play;

import sul.utils.*;

public class PlayerHotbar extends Packet {

	public static final int ID = (int)48;

	public static final boolean CLIENTBOUND = false;
	public static final boolean SERVERBOUND = false;

	@Override
	public int getId() {
		return ID;
	}

	@Override
	public int length() {
		return 1;
	}

	@Override
	public byte[] encode() {
		this._buffer = new byte[this.length()];
		this.writeVaruint(ID);
		return this.getBuffer();
	}

	@Override
	public void decode(byte[] buffer) {
		this._buffer = buffer;
		this.readVaruint();
	}

	public static PlayerHotbar fromBuffer(byte[] buffer) {
		PlayerHotbar ret = new PlayerHotbar();
		ret.decode(buffer);
		return ret;
	}

	@Override
	public String toString() {
		return "PlayerHotbar()";
	}

}