/*
 * This file was automatically generated by sel-utils and
 * released under the MIT License.
 * 
 * License: https://github.com/sel-project/sel-utils/blob/master/LICENSE
 * Repository: https://github.com/sel-project/sel-utils
 * Generated from https://github.com/sel-project/sel-utils/blob/master/xml/protocol/java338.xml
 */
package sul.protocol.java338.clientbound;

import sul.utils.*;

public class CraftRecipeResponse extends Packet {

	public static final int ID = (int)43;

	public static final boolean CLIENTBOUND = true;
	public static final boolean SERVERBOUND = false;

	@Override
	public int getId() {
		return ID;
	}

	public byte window;
	public int recipe;

	public CraftRecipeResponse() {}

	public CraftRecipeResponse(byte window, int recipe) {
		this.window = window;
		this.recipe = recipe;
	}

	@Override
	public int length() {
		return Buffer.varuintLength(recipe) + 2;
	}

	@Override
	public byte[] encode() {
		this._buffer = new byte[this.length()];
		this.writeVaruint(ID);
		this.writeBigEndianByte(window);
		this.writeVaruint(recipe);
		return this.getBuffer();
	}

	@Override
	public void decode(byte[] buffer) {
		this._buffer = buffer;
		this.readVaruint();
		window=readBigEndianByte();
		recipe=this.readVaruint();
	}

	public static CraftRecipeResponse fromBuffer(byte[] buffer) {
		CraftRecipeResponse ret = new CraftRecipeResponse();
		ret.decode(buffer);
		return ret;
	}

	@Override
	public String toString() {
		return "CraftRecipeResponse(window: " + this.window + ", recipe: " + this.recipe + ")";
	}

}