/*
 * This file was automatically generated by sel-utils and
 * released under the MIT License.
 * 
 * License: https://github.com/sel-project/sel-utils/blob/master/LICENSE
 * Repository: https://github.com/sel-project/sel-utils
 * Generated from https://github.com/sel-project/sel-utils/blob/master/xml/protocol/bedrock137.xml
 */
package sul.protocol.bedrock137.play;

import java.nio.charset.StandardCharsets;

import sul.utils.*;

public class StopSound extends Packet {

	public static final int ID = (int)87;

	public static final boolean CLIENTBOUND = true;
	public static final boolean SERVERBOUND = false;

	@Override
	public int getId() {
		return ID;
	}

	public String name;
	public boolean stopAll;

	public StopSound() {}

	public StopSound(String name, boolean stopAll) {
		this.name = name;
		this.stopAll = stopAll;
	}

	@Override
	public int length() {
		return Buffer.varuintLength(name.getBytes(StandardCharsets.UTF_8).length) + name.getBytes(StandardCharsets.UTF_8).length + 3;
	}

	@Override
	public byte[] encode() {
		this._buffer = new byte[this.length()];
		this.writeVaruint(ID);
		byte[] bfz=name.getBytes(StandardCharsets.UTF_8); this.writeVaruint((int)bfz.length); this.writeBytes(bfz);
		this.writeBool(stopAll);
		return this.getBuffer();
	}

	@Override
	public void decode(byte[] buffer) {
		this._buffer = buffer;
		this.readVaruint();
		int bvbfz=this.readVaruint(); name=new String(this.readBytes(bvbfz), StandardCharsets.UTF_8);
		stopAll=this.readBool();
	}

	public static StopSound fromBuffer(byte[] buffer) {
		StopSound ret = new StopSound();
		ret.decode(buffer);
		return ret;
	}

	@Override
	public String toString() {
		return "StopSound(name: " + this.name + ", stopAll: " + this.stopAll + ")";
	}

}