/*
 * This file was automatically generated by sel-utils and
 * released under the MIT License.
 * 
 * License: https://github.com/sel-project/sel-utils/blob/master/LICENSE
 * Repository: https://github.com/sel-project/sel-utils
 * Generated from https://github.com/sel-project/sel-utils/blob/master/xml/protocol/pocket113.xml
 */
package sul.protocol.pocket113.play;

import sul.utils.*;

public class Login extends Packet {

	public static final byte ID = (byte)1;

	public static final boolean CLIENTBOUND = false;
	public static final boolean SERVERBOUND = true;

	@Override
	public int getId() {
		return ID;
	}

	// version
	public static final byte VANILLA = (byte)0;
	public static final byte EDUCATION = (byte)1;

	public int protocol = 113;
	public byte version;
	public sul.protocol.pocket113.types.LoginBody body;

	public Login() {}

	public Login(int protocol, byte version, sul.protocol.pocket113.types.LoginBody body) {
		this.protocol = protocol;
		this.version = version;
		this.body = body;
	}

	@Override
	public int length() {
		return body.length() + 6;
	}

	@Override
	public byte[] encode() {
		this._buffer = new byte[this.length()];
		this.writeBigEndianByte(ID);
		this.writeBigEndianInt(protocol);
		this.writeBigEndianByte(version);
		this.writeBytes(body.encode());
		return this.getBuffer();
	}

	@Override
	public void decode(byte[] buffer) {
		this._buffer = buffer;
		readBigEndianByte();
		protocol=readBigEndianInt();
		version=readBigEndianByte();
		body=new sul.protocol.pocket113.types.LoginBody(); body._index=this._index; body.decode(this._buffer); this._index=body._index;
	}

	public static Login fromBuffer(byte[] buffer) {
		Login ret = new Login();
		ret.decode(buffer);
		return ret;
	}

	@Override
	public String toString() {
		return "Login(protocol: " + this.protocol + ", version: " + this.version + ", body: " + this.body.toString() + ")";
	}

}