/*
 * This file was automatically generated by sel-utils and
 * released under the GNU General Public License version 3.
 * 
 * License: https://github.com/sel-project/sel-utils/blob/master/LICENSE
 * Repository: https://github.com/sel-project/sel-utils
 * Generated from https://github.com/sel-project/sel-utils/blob/master/xml/protocol/pocket100.xml
 */
package sul.protocol.pocket100.play;

import java.nio.charset.StandardCharsets;

import sul.utils.*;

public class CommandStep extends Packet {

	public static final byte ID = (byte)78;

	public static final boolean CLIENTBOUND = false;
	public static final boolean SERVERBOUND = true;

	@Override
	public int getId() {
		return ID;
	}

	public String command;
	public String overload;
	public int unknown2;
	public int currentStep;
	public boolean done;
	public long clientId;
	public sul.protocol.pocket100.types.Json input;
	public sul.protocol.pocket100.types.Json output;

	public CommandStep() {}

	public CommandStep(String command, String overload, int unknown2, int currentStep, boolean done, long clientId, sul.protocol.pocket100.types.Json input, sul.protocol.pocket100.types.Json output) {
		this.command = command;
		this.overload = overload;
		this.unknown2 = unknown2;
		this.currentStep = currentStep;
		this.done = done;
		this.clientId = clientId;
		this.input = input;
		this.output = output;
	}

	@Override
	public int length() {
		return Buffer.varuintLength(command.getBytes(StandardCharsets.UTF_8).length) + command.getBytes(StandardCharsets.UTF_8).length + Buffer.varuintLength(overload.getBytes(StandardCharsets.UTF_8).length) + overload.getBytes(StandardCharsets.UTF_8).length + Buffer.varuintLength(unknown2) + Buffer.varuintLength(currentStep) + Buffer.varulongLength(clientId) + input.length() + output.length() + 2;
	}

	@Override
	public byte[] encode() {
		this._buffer = new byte[this.length()];
		this.writeBigEndianByte(ID);
		byte[] y9bfz=command.getBytes(StandardCharsets.UTF_8); this.writeVaruint((int)y9bfz.length); this.writeBytes(y9bfz);
		byte[] bzcxyq=overload.getBytes(StandardCharsets.UTF_8); this.writeVaruint((int)bzcxyq.length); this.writeBytes(bzcxyq);
		this.writeVaruint(unknown2);
		this.writeVaruint(currentStep);
		this.writeBool(done);
		this.writeVarulong(clientId);
		this.writeBytes(input.encode());
		this.writeBytes(output.encode());
		return this.getBuffer();
	}

	@Override
	public void decode(byte[] buffer) {
		this._buffer = buffer;
		readBigEndianByte();
		int bvy9bfz=this.readVaruint(); command=new String(this.readBytes(bvy9bfz), StandardCharsets.UTF_8);
		int bvbzcxyq=this.readVaruint(); overload=new String(this.readBytes(bvbzcxyq), StandardCharsets.UTF_8);
		unknown2=this.readVaruint();
		currentStep=this.readVaruint();
		done=this.readBool();
		clientId=this.readVarulong();
		input=new sul.protocol.pocket100.types.Json(); input._index=this._index; input.decode(this._buffer); this._index=input._index;
		output=new sul.protocol.pocket100.types.Json(); output._index=this._index; output.decode(this._buffer); this._index=output._index;
	}

	public static CommandStep fromBuffer(byte[] buffer) {
		CommandStep ret = new CommandStep();
		ret.decode(buffer);
		return ret;
	}

	@Override
	public String toString() {
		return "CommandStep(command: " + this.command + ", overload: " + this.overload + ", unknown2: " + this.unknown2 + ", currentStep: " + this.currentStep + ", done: " + this.done + ", clientId: " + this.clientId + ", input: " + this.input.toString() + ", output: " + this.output.toString() + ")";
	}

}