/*
 * This file was automatically generated by sel-utils and
 * released under the MIT License.
 * 
 * License: https://github.com/sel-project/sel-utils/blob/master/LICENSE
 * Repository: https://github.com/sel-project/sel-utils
 * Generated from https://github.com/sel-project/sel-utils/blob/master/xml/entities.xml
 */
package sul;

import java.util.Map;
import java.util.HashMap;

public enum Entities
{

    BOAT("boat", true, 1, 90, 1.5, 0.6),
    DROPPED_ITEM("dropped item", true, 2, 64, 0.25, 0.25),
    EXPERIENCE_ORB("experience orb", true, 2, 69, 0.25, 0.25),
    AREA_EFFECT_CLOUD("area effect cloud", true, 3, 95, 2, 0.5),
    MINECART("minecart", true, 10, 84, 0.98, 0.7),
    MINECART_WITH_HOPPER("minecart with hopper", true, 0, 96, 0.98, 0.7),
    MINECART_WITH_TNT("minecart with tnt", true, 0, 97, 0.98, 0.7),
    MINECART_WITH_CHEST("minecart with chest", true, 0, 98, 0.98, 0.7),
    MINECART_WITH_COMMAND_BLOCK("minecart with command block", true, 0, 100, 0.98, 0.7),
    ACTIVATED_TNT("activated tnt", true, 50, 65, 0.98, 0.98),
    ENDER_CRYSTAL("ender crystal", true, 51, 71, 2, 2),
    ARROW("arrow", true, 60, 80, 0.5, 0.5),
    SNOWBALL("snowball", true, 61, 81, 0.25, 0.25),
    EGG("egg", true, 62, 82, 0.25, 0.25),
    GHAST_FIREBALL("ghast fireball", true, 63, 85, 1, 1),
    BLAZE_FIREBALL("blaze fireball", true, 64, 94, 0.3125, 0.3125),
    ENDERPEARL("enderpearl", true, 65, 87, 0.25, 0.25),
    WITHER_SKULL("wither skull", true, 66, 89, 0.3125, 0.3125),
    SHULKER_BULLET("shulker bullet", true, 67, 76, 0.3125, 0.3125),
    LLAMA_SPIT("llama spit", true, 68, 102, 0.25, 0.25),
    FALLING_BLOCK("falling block", true, 70, 66, 0.98, 0.98),
    ITEM_FRAME("item frame", true, 71, 0),
    EYE_OF_ENDER("eye of ender", true, 72, 70, 0.25, 0.25),
    SPLASH_POTION("splash potion", true, 73, 86, 0.25, 0.25),
    EXP_BOTTLE("exp bottle", true, 75, 68, 0.25, 0.25),
    FIREWORK_ROCKET("firework rocket", true, 76, 0, 0.25, 0.25),
    LEASH_KNOT("leash knot", true, 77, 88, 0.375, 0.25),
    ARMOR_STAND("armor stand", true, 78, 0, 0.5, 1.975),
    EVOCATION_FANGS("evocation fangs", true, 79, 103, 0.5, 0.8),
    FISHING_HOOK("fishing hook", true, 0, 77, 0.25, 0.25),
    SPECTRAL_ARROW("spectral arrow", true, 91, 0, 0.5, 0.5),
    DRAGON_FIREBALL("dragon fireball", true, 93, 79, 1, 1),
    CAMERA("camera", true, 0, 62),
    PAINTING("painting", true, 0, 83),
    LIGHTNING("lightning", true, 0, 93),
    ELDER_GUARDIAN("elder guardian", false, 4, 50, 1.9975, 1.9975),
    WITHER_SKELETON("wither skeleton", false, 5, 48, 0.7, 2.4),
    STRAY("stray", false, 6, 46, 0.6, 1.99),
    HUSK("husk", false, 23, 47, 0.6, 1.99),
    ZOMBIE_VILLAGER("zombie villager", false, 27, 44, 0.6, 1.95),
    SKELETON_HORSE("skeleton horse", false, 28, 26, 1.39648, 1.6),
    ZOMBIE_HORSE("zombie horse", false, 29, 27, 1.39648, 1.6),
    DONKEY("donkey", false, 31, 24, 1.39648, 1.6),
    MULE("mule", false, 32, 25, 1.39648, 1.6),
    EVOKER("evoker", false, 34, 104, 0.6, 1.95),
    VEX("vex", false, 35, 105, 0.4, 0.8),
    VINDICATOR("vindicator", false, 36, 56, 0.6, 1.95),
    ILLUSIONER("illusioner", false, 37, 0, 0.6, 1.95),
    CREEPER("creeper", false, 50, 33, 0.6, 1.7),
    SKELETON("skeleton", false, 0, 34, 0.6, 1.99),
    SPIDER("spider", false, 52, 35, 1.4, 0.9),
    GIANT("giant", false, 53, 0, 3.6, 10.8),
    ZOMBIE("zombie", false, 54, 32, 0.6, 1.95),
    SLIME("slime", false, 55, 37, 0.51, 0.51),
    GHAST("ghast", false, 56, 41, 4, 4),
    ENDERMAN("enderman", false, 58, 38, 0.6, 2.9),
    CAVE_SPIDER("cave spider", false, 59, 40, 0.7, 0.5),
    SILVERFISH("silverfish", false, 60, 39, 0.4, 0.3),
    BLAZE("blaze", false, 61, 43, 0.6, 1.8),
    MAGMA_CUBE("magma cube", false, 62, 42, 0.51, 0.51),
    ENDER_DRAGON("ender dragon", false, 63, 53, 16, 8),
    WITHER_BOSS("wither boss", false, 64, 52, 0.9, 3.5),
    BAT("bat", false, 65, 19, 0.5, 0.9),
    WITCH("witch", false, 66, 45, 0.6, 1.95),
    ENDERMITE("endermite", false, 67, 55, 0.4, 0.3),
    GUARDIAN("guardian", false, 68, 49, 0.85, 0.85),
    SHULKER("shulker", false, 69, 54, 1, 1),
    PIG("pig", false, 90, 12, 0.9, 0.9),
    SHEEP("sheep", false, 91, 13, 0.9, 1.3),
    COW("cow", false, 92, 11, 0.9, 1.4),
    CHICKEN("chicken", false, 93, 10, 0.4, 0.7),
    SQUID("squid", false, 94, 17, 0.8, 0.8),
    WOLF("wolf", false, 95, 14, 0.6, 0.85),
    MOOSHROOM("mooshroom", false, 96, 16, 0.9, 1.4),
    SNOW_GOLEM("snow golem", false, 97, 21, 0.7, 1.9),
    OCELOT("ocelot", false, 98, 22, 0.6, 0.7),
    IRON_GOLEM("iron golem", false, 99, 20, 1.4, 2.7),
    HORSE("horse", false, 100, 23, 1.39648, 1.6),
    RABBIT("rabbit", false, 101, 18, 0.4, 0.5),
    POLAR_BEAR("polar bear", false, 102, 28, 1.3, 1.4),
    LLAMA("llama", false, 103, 29, 0.9, 1.87),
    PARROT("parrot", false, 105, 0, 0.5, 1),
    VILLAGER("villager", false, 120, 15, 0.6, 1.95),
    NPC("npc", false, 0, 51, 0.6, 1.95);

    public final String name;
    public final boolean object;
    public final int minecraft, pocket;
    public final double width, height;

    Entities(String name, boolean object, int minecraft, int pocket, double width, double height)
    {
        this.name = name;
        this.object = object;
        this.minecraft = minecraft;
        this.pocket = pocket;
        this.width = width;
        this.height = height;
    }

    Entities(String name, boolean object, int minecraft, int pocket)
    {
        this(name, object, minecraft, pocket, Double.NaN, Double.NaN);
    }

    private static Map<Integer, Entities> minecraftEntities, minecraftObjects, pocketEntities, pocketObjects;

    static
    {

        minecraftEntities = new HashMap<Integer, Entities>();
        minecraftObjects = new HashMap<Integer, Entities>();
        pocketEntities = new HashMap<Integer, Entities>();
        pocketObjects = new HashMap<Integer, Entities>();

        add(BOAT);
        add(DROPPED_ITEM);
        add(EXPERIENCE_ORB);
        add(AREA_EFFECT_CLOUD);
        add(MINECART);
        add(MINECART_WITH_HOPPER);
        add(MINECART_WITH_TNT);
        add(MINECART_WITH_CHEST);
        add(MINECART_WITH_COMMAND_BLOCK);
        add(ACTIVATED_TNT);
        add(ENDER_CRYSTAL);
        add(ARROW);
        add(SNOWBALL);
        add(EGG);
        add(GHAST_FIREBALL);
        add(BLAZE_FIREBALL);
        add(ENDERPEARL);
        add(WITHER_SKULL);
        add(SHULKER_BULLET);
        add(LLAMA_SPIT);
        add(FALLING_BLOCK);
        add(ITEM_FRAME);
        add(EYE_OF_ENDER);
        add(SPLASH_POTION);
        add(EXP_BOTTLE);
        add(FIREWORK_ROCKET);
        add(LEASH_KNOT);
        add(ARMOR_STAND);
        add(EVOCATION_FANGS);
        add(FISHING_HOOK);
        add(SPECTRAL_ARROW);
        add(DRAGON_FIREBALL);
        add(CAMERA);
        add(PAINTING);
        add(LIGHTNING);
        add(ELDER_GUARDIAN);
        add(WITHER_SKELETON);
        add(STRAY);
        add(HUSK);
        add(ZOMBIE_VILLAGER);
        add(SKELETON_HORSE);
        add(ZOMBIE_HORSE);
        add(DONKEY);
        add(MULE);
        add(EVOKER);
        add(VEX);
        add(VINDICATOR);
        add(ILLUSIONER);
        add(CREEPER);
        add(SKELETON);
        add(SPIDER);
        add(GIANT);
        add(ZOMBIE);
        add(SLIME);
        add(GHAST);
        add(ENDERMAN);
        add(CAVE_SPIDER);
        add(SILVERFISH);
        add(BLAZE);
        add(MAGMA_CUBE);
        add(ENDER_DRAGON);
        add(WITHER_BOSS);
        add(BAT);
        add(WITCH);
        add(ENDERMITE);
        add(GUARDIAN);
        add(SHULKER);
        add(PIG);
        add(SHEEP);
        add(COW);
        add(CHICKEN);
        add(SQUID);
        add(WOLF);
        add(MOOSHROOM);
        add(SNOW_GOLEM);
        add(OCELOT);
        add(IRON_GOLEM);
        add(HORSE);
        add(RABBIT);
        add(POLAR_BEAR);
        add(LLAMA);
        add(PARROT);
        add(VILLAGER);
        add(NPC);

    }

    private static void add(Entities entity)
    {
        if(entity.minecraft > 0)
        {
            if(entity.object) minecraftObjects.put(entity.minecraft, entity);
            if(!entity.object || !minecraftEntities.containsKey(entity.minecraft)) minecraftEntities.put(entity.minecraft, entity);
        }
        if(entity.pocket > 0)
        {
            if(entity.object) pocketObjects.put(entity.pocket, entity);
            if(!entity.object || !pocketEntities.containsKey(entity.pocket)) pocketEntities.put(entity.pocket, entity);
        }
    }

    public static Entities getMinecraftEntity(int id, boolean object)
    {
        if(object && minecraftObjects.containsKey(id)) return minecraftObjects.get(id);
        else return minecraftEntities.get(id);
    }

    public static Entities getMinecraftEntity(int id)
    {
        return getMinecraftEntity(id, false);
    }

    public static Entities getMinecraftObject(int id)
    {
        return getMinecraftEntity(id, true);
    }

    public static Entities getPocketEntity(int id, boolean object)
    {
        if(object && pocketObjects.containsKey(id)) return pocketObjects.get(id);
        else return pocketEntities.get(id);
    }

    public static Entities getPocketEntity(int id)
    {
        return getPocketEntity(id, false);
    }

    public static Entities getPocketObject(int id)
    {
        return getPocketEntity(id, true);
    }

}
