/*
 * This file was automatically generated by sel-utils and
 * released under the MIT License.
 * 
 * License: https://github.com/sel-project/sel-utils/blob/master/LICENSE
 * Repository: https://github.com/sel-project/sel-utils
 * Generated from https://github.com/sel-project/sel-utils/blob/master/xml/protocol/pocket111.xml
 */
package sul.protocol.pocket111.play;

import sul.utils.*;

/**
 * First MCPE packet sent after the establishment of the connection through raknet.
 * It contains informations about the player.
 */
public class Login extends Packet {

	public static final byte ID = (byte)1;

	public static final boolean CLIENTBOUND = false;
	public static final boolean SERVERBOUND = true;

	@Override
	public int getId() {
		return ID;
	}

	// version
	public static final byte VANILLA = 0;
	public static final byte EDUCATION = 1;

	/**
	 * Version of the protocol used by the player.
	 */
	public int protocol = 111;

	/**
	 * Edition that the player is using to join the server. The different editions may
	 * have different features and servers may block the access from unaccepted editions
	 * of the game.
	 */
	public byte version;

	/**
	 * Length, in bytes, of the following field. This field was used when the body was
	 * compressed.
	 */
	public int bodyLength;

	/**
	 * Payload that contains 2 JWTs (with each length indicated by an unsigned little-endian
	 * 32-bits integer) with more informations about the player and its account.
	 */
	public sul.protocol.pocket111.types.LoginBody body;

	public Login() {}

	public Login(int protocol, byte version, int bodyLength, sul.protocol.pocket111.types.LoginBody body) {
		this.protocol = protocol;
		this.version = version;
		this.bodyLength = bodyLength;
		this.body = body;
	}

	@Override
	public int length() {
		return Buffer.varuintLength(bodyLength) + body.length() + 6;
	}

	@Override
	public byte[] encode() {
		this._buffer = new byte[this.length()];
		this.writeBigEndianByte(ID);
		this.writeBigEndianInt(protocol);
		this.writeBigEndianByte(version);
		this.writeVaruint(bodyLength);
		this.writeBytes(body.encode());
		return this.getBuffer();
	}

	@Override
	public void decode(byte[] buffer) {
		this._buffer = buffer;
		readBigEndianByte();
		protocol=readBigEndianInt();
		version=readBigEndianByte();
		bodyLength=this.readVaruint();
		body=new sul.protocol.pocket111.types.LoginBody(); body._index=this._index; body.decode(this._buffer); this._index=body._index;
	}

	public static Login fromBuffer(byte[] buffer) {
		Login ret = new Login();
		ret.decode(buffer);
		return ret;
	}

	@Override
	public String toString() {
		return "Login(protocol: " + this.protocol + ", version: " + this.version + ", bodyLength: " + this.bodyLength + ", body: " + this.body.toString() + ")";
	}

}