/*
 * This file was automatically generated by sel-utils and
 * released under the MIT License.
 * 
 * License: https://github.com/sel-project/sel-utils/blob/master/LICENSE
 * Repository: https://github.com/sel-project/sel-utils
 */
package sul.protocol.bedrock137;

import java.util.Collections;
import java.util.Map;
import java.util.HashMap;

import sul.utils.Packet;

public final class Packets {

	private Packets() {}

	public static final Map<Integer, Class<? extends Packet>> PLAY;

	static {

		HashMap<Integer, Class<? extends Packet>> play = new HashMap<Integer, Class<? extends Packet>>();
		play.put(1, sul.protocol.bedrock137.play.Login.class);
		play.put(2, sul.protocol.bedrock137.play.PlayStatus.class);
		play.put(3, sul.protocol.bedrock137.play.ServerToClientHandshake.class);
		play.put(4, sul.protocol.bedrock137.play.ClientToServerHandshake.class);
		play.put(5, sul.protocol.bedrock137.play.Disconnect.class);
		play.put(6, sul.protocol.bedrock137.play.ResourcePacksInfo.class);
		play.put(7, sul.protocol.bedrock137.play.ResourcePacksStackPacket.class);
		play.put(8, sul.protocol.bedrock137.play.ResourcePackClientResponse.class);
		play.put(9, sul.protocol.bedrock137.play.Text.class);
		play.put(10, sul.protocol.bedrock137.play.SetTime.class);
		play.put(11, sul.protocol.bedrock137.play.StartGame.class);
		play.put(12, sul.protocol.bedrock137.play.AddPlayer.class);
		play.put(13, sul.protocol.bedrock137.play.AddEntity.class);
		play.put(14, sul.protocol.bedrock137.play.RemoveEntity.class);
		play.put(15, sul.protocol.bedrock137.play.AddItemEntity.class);
		play.put(16, sul.protocol.bedrock137.play.AddHangingEntity.class);
		play.put(17, sul.protocol.bedrock137.play.TakeItemEntity.class);
		play.put(18, sul.protocol.bedrock137.play.MoveEntity.class);
		play.put(19, sul.protocol.bedrock137.play.MovePlayer.class);
		play.put(20, sul.protocol.bedrock137.play.RiderJump.class);
		play.put(21, sul.protocol.bedrock137.play.UpdateBlock.class);
		play.put(22, sul.protocol.bedrock137.play.AddPainting.class);
		play.put(23, sul.protocol.bedrock137.play.Explode.class);
		play.put(24, sul.protocol.bedrock137.play.LevelSoundEvent.class);
		play.put(25, sul.protocol.bedrock137.play.LevelEvent.class);
		play.put(26, sul.protocol.bedrock137.play.BlockEvent.class);
		play.put(27, sul.protocol.bedrock137.play.EntityEvent.class);
		play.put(28, sul.protocol.bedrock137.play.MobEffect.class);
		play.put(29, sul.protocol.bedrock137.play.UpdateAttributes.class);
		play.put(30, sul.protocol.bedrock137.play.InventoryTransaction.class);
		play.put(31, sul.protocol.bedrock137.play.MobEquipment.class);
		play.put(32, sul.protocol.bedrock137.play.MobArmorEquipment.class);
		play.put(33, sul.protocol.bedrock137.play.Interact.class);
		play.put(34, sul.protocol.bedrock137.play.BlockPickRequest.class);
		play.put(35, sul.protocol.bedrock137.play.EntityPickRequest.class);
		play.put(36, sul.protocol.bedrock137.play.PlayerAction.class);
		play.put(37, sul.protocol.bedrock137.play.EntityFall.class);
		play.put(38, sul.protocol.bedrock137.play.HurtArmor.class);
		play.put(39, sul.protocol.bedrock137.play.SetEntityData.class);
		play.put(40, sul.protocol.bedrock137.play.SetEntityMotion.class);
		play.put(41, sul.protocol.bedrock137.play.SetEntityLink.class);
		play.put(42, sul.protocol.bedrock137.play.SetHealth.class);
		play.put(43, sul.protocol.bedrock137.play.SetSpawnPosition.class);
		play.put(44, sul.protocol.bedrock137.play.Animate.class);
		play.put(45, sul.protocol.bedrock137.play.Respawn.class);
		play.put(46, sul.protocol.bedrock137.play.ContainerOpen.class);
		play.put(47, sul.protocol.bedrock137.play.ContainerClose.class);
		play.put(48, sul.protocol.bedrock137.play.PlayerHotbar.class);
		play.put(49, sul.protocol.bedrock137.play.InventoryContent.class);
		play.put(50, sul.protocol.bedrock137.play.InventorySlot.class);
		play.put(51, sul.protocol.bedrock137.play.ContainerSetData.class);
		play.put(52, sul.protocol.bedrock137.play.CraftingData.class);
		play.put(53, sul.protocol.bedrock137.play.CraftingEvent.class);
		play.put(54, sul.protocol.bedrock137.play.GuiDataPickItem.class);
		play.put(55, sul.protocol.bedrock137.play.AdventureSettings.class);
		play.put(56, sul.protocol.bedrock137.play.BlockEntityData.class);
		play.put(57, sul.protocol.bedrock137.play.PlayerInput.class);
		play.put(58, sul.protocol.bedrock137.play.FullChunkData.class);
		play.put(59, sul.protocol.bedrock137.play.SetCommandsEnabled.class);
		play.put(60, sul.protocol.bedrock137.play.SetDifficulty.class);
		play.put(61, sul.protocol.bedrock137.play.ChangeDimension.class);
		play.put(62, sul.protocol.bedrock137.play.SetPlayerGameType.class);
		play.put(63, sul.protocol.bedrock137.play.PlayerList.class);
		play.put(64, sul.protocol.bedrock137.play.SimpleEvent.class);
		play.put(65, sul.protocol.bedrock137.play.TelemetryEvent.class);
		play.put(66, sul.protocol.bedrock137.play.SpawnExperienceOrb.class);
		play.put(67, sul.protocol.bedrock137.play.ClientboundMapItemData.class);
		play.put(68, sul.protocol.bedrock137.play.MapInfoRequest.class);
		play.put(69, sul.protocol.bedrock137.play.RequestChunkRadius.class);
		play.put(70, sul.protocol.bedrock137.play.ChunkRadiusUpdated.class);
		play.put(71, sul.protocol.bedrock137.play.ItemFrameDropItem.class);
		play.put(72, sul.protocol.bedrock137.play.GameRulesChanged.class);
		play.put(73, sul.protocol.bedrock137.play.Camera.class);
		play.put(74, sul.protocol.bedrock137.play.BossEvent.class);
		play.put(75, sul.protocol.bedrock137.play.ShowCredits.class);
		play.put(76, sul.protocol.bedrock137.play.AvailableCommands.class);
		play.put(77, sul.protocol.bedrock137.play.CommandRequest.class);
		play.put(78, sul.protocol.bedrock137.play.CommandBlockUpdate.class);
		play.put(80, sul.protocol.bedrock137.play.UpdateTrade.class);
		play.put(81, sul.protocol.bedrock137.play.UpdateEquip.class);
		play.put(82, sul.protocol.bedrock137.play.ResourcePackDataInfo.class);
		play.put(83, sul.protocol.bedrock137.play.ResourcePackChunkData.class);
		play.put(84, sul.protocol.bedrock137.play.ResourcePackChunkRequest.class);
		play.put(85, sul.protocol.bedrock137.play.Transfer.class);
		play.put(86, sul.protocol.bedrock137.play.PlaySound.class);
		play.put(87, sul.protocol.bedrock137.play.StopSound.class);
		play.put(88, sul.protocol.bedrock137.play.SetTitle.class);
		play.put(89, sul.protocol.bedrock137.play.AddBehaviorTree.class);
		play.put(90, sul.protocol.bedrock137.play.StructureBlockUpdate.class);
		play.put(91, sul.protocol.bedrock137.play.ShowStoreOffer.class);
		play.put(92, sul.protocol.bedrock137.play.PurchaseReceipt.class);
		play.put(93, sul.protocol.bedrock137.play.PlayerSkin.class);
		play.put(94, sul.protocol.bedrock137.play.SubClientLogin.class);
		play.put(95, sul.protocol.bedrock137.play.InitiateWebSocketConnection.class);
		play.put(96, sul.protocol.bedrock137.play.SetLastHurtBy.class);
		play.put(97, sul.protocol.bedrock137.play.BookEdit.class);
		play.put(98, sul.protocol.bedrock137.play.NpcRequest.class);
		play.put(99, sul.protocol.bedrock137.play.PhotoTransfer.class);
		play.put(100, sul.protocol.bedrock137.play.ModalFormRequest.class);
		play.put(101, sul.protocol.bedrock137.play.ModalFormResponse.class);
		play.put(102, sul.protocol.bedrock137.play.ServerSettingsRequest.class);
		play.put(103, sul.protocol.bedrock137.play.ServerSettingsResponse.class);
		play.put(104, sul.protocol.bedrock137.play.ShowProfile.class);
		play.put(105, sul.protocol.bedrock137.play.SetDefaultGameType.class);
		PLAY = Collections.unmodifiableMap(play);

	}

}