/*
 * This file was automatically generated by sel-utils and
 * released under the MIT License.
 * 
 * License: https://github.com/sel-project/sel-utils/blob/master/LICENSE
 * Repository: https://github.com/sel-project/sel-utils
 * Generated from https://github.com/sel-project/sel-utils/blob/master/xml/protocol/pocket133.xml
 */
package sul.protocol.pocket133.play;

import sul.utils.*;

/**
 * Spawns a dropped item.
 */
public class AddItemEntity extends Packet {

	public static final int ID = (int)15;

	public static final boolean CLIENTBOUND = true;
	public static final boolean SERVERBOUND = false;

	@Override
	public int getId() {
		return ID;
	}

	public long entityId;
	public long runtimeId;
	public sul.protocol.pocket133.types.Slot item;
	public Tuples.FloatXYZ position = new Tuples.FloatXYZ();
	public Tuples.FloatXYZ motion = new Tuples.FloatXYZ();
	public sul.metadata.Pocket133 metadata;

	public AddItemEntity() {}

	public AddItemEntity(long entityId, long runtimeId, sul.protocol.pocket133.types.Slot item, Tuples.FloatXYZ position, Tuples.FloatXYZ motion, sul.metadata.Pocket133 metadata) {
		this.entityId = entityId;
		this.runtimeId = runtimeId;
		this.item = item;
		this.position = position;
		this.motion = motion;
		this.metadata = metadata;
	}

	@Override
	public int length() {
		return Buffer.varlongLength(entityId) + Buffer.varulongLength(runtimeId) + item.length() + metadata.length() + 25;
	}

	@Override
	public byte[] encode() {
		this._buffer = new byte[this.length()];
		this.writeVaruint(ID);
		this.writeVarlong(entityId);
		this.writeVarulong(runtimeId);
		this.writeBytes(item.encode());
		this.writeLittleEndianFloat(position.x); this.writeLittleEndianFloat(position.y); this.writeLittleEndianFloat(position.z);
		this.writeLittleEndianFloat(motion.x); this.writeLittleEndianFloat(motion.y); this.writeLittleEndianFloat(motion.z);
		this.writeBytes(metadata.encode());
		return this.getBuffer();
	}

	@Override
	public void decode(byte[] buffer) {
		this._buffer = buffer;
		this.readVaruint();
		entityId=this.readVarlong();
		runtimeId=this.readVarulong();
		item=new sul.protocol.pocket133.types.Slot(); item._index=this._index; item.decode(this._buffer); this._index=item._index;
		position=new Tuples.FloatXYZ(); position.x=readLittleEndianFloat(); position.y=readLittleEndianFloat(); position.z=readLittleEndianFloat();
		motion=new Tuples.FloatXYZ(); motion.x=readLittleEndianFloat(); motion.y=readLittleEndianFloat(); motion.z=readLittleEndianFloat();
		metadata=new sul.metadata.Pocket133(); metadata._index=this._index; metadata.decode(this._buffer); this._index=metadata._index;
	}

	public static AddItemEntity fromBuffer(byte[] buffer) {
		AddItemEntity ret = new AddItemEntity();
		ret.decode(buffer);
		return ret;
	}

	@Override
	public String toString() {
		return "AddItemEntity(entityId: " + this.entityId + ", runtimeId: " + this.runtimeId + ", item: " + this.item.toString() + ", position: " + this.position.toString() + ", motion: " + this.motion.toString() + ", metadata: " + this.metadata.toString() + ")";
	}

}