/*
 * This file was automatically generated by sel-utils and
 * released under the GNU General Public License version 3.
 * 
 * License: https://github.com/sel-project/sel-utils/blob/master/LICENSE
 * Repository: https://github.com/sel-project/sel-utils
 * Generated from https://github.com/sel-project/sel-utils/blob/master/xml/attributes/pocket105.xml
 */
package sul.attributes;

public enum Pocket105 {

	MINECRAFT:HEALTH("health", 0f, 20f, 20f),

	MINECRAFT:GENERIC.ABSORPTION("absorption", 0f, 4f, 0f),

	MINECRAFT:PLAYER.HUNGER("hunger", 0f, 20f, 20f),

	MINECRAFT:PLAYER.SATURATION("saturation", 0f, 20f, 5f),

	MINECRAFT:PLAYER.EXPERIENCE("experience", 0f, 1f, 0f),

	MINECRAFT:PLAYER.LEVEL("level", 0f, 24791f, 0f),

	MINECRAFT:MOVEMENT("speed", 0f, 24791f, 0.1f),

	MINECRAFT:GENERIC.KNOCKBACK_RESISTANCE("knockback_resistance", 0f, 1f, 0f);

	public final String name;
	public final float min, max, def;

	Pocket105(String name, float min, float max, float def) {
		this.name = name;
		this.min = min;
		this.max = max;
		this.def = def;
	}

}