/*
 * This file was automatically generated by sel-utils and
 * released under the MIT License.
 * 
 * License: https://github.com/sel-project/sel-utils/blob/master/LICENSE
 * Repository: https://github.com/sel-project/sel-utils
 * Generated from https://github.com/sel-project/sel-utils/blob/master/xml/protocol/hncom2.xml
 */
package sul.protocol.hncom2.types;

import sul.utils.*;

public class Property extends Stream {

	@Override
	public int length() {
		return 0;
	}

	@Override
	public byte[] encode() {
		this._buffer = new byte[this.length()];
		return this.getBuffer();
	}

	@Override
	public void decode(byte[] buffer) {
		this._buffer = buffer;
	}

	@Override
	public String toString() {
		return "Property()";
	}


}